### ISSUE TITLE
Is This Open Source?

### ISSUE THREAD

**Issue by HangingClowns** [devcartel/pyrfa#18]
Originally, I wanted to prepare a requirements.txt file, but I noticed that this package is NOT listed on pip, so I was going to try to link to your github code, but it seems it's also not here...

Is there any recommended way to add this file to requirements.txt?

**Comment by ehouarn-perret** [comment]
@HangingClowns I'm suspecting it's not and since there is no source available whatsoever, this is probably not open.

**Comment by HangingClowns** [comment]
@ehouarn-perret yeah, I just looked more in to the library. They're compiled libraries. I have no problem against that, just wish there was an automated way for us to use pip to get that library installed.

**Comment by ukrit-himakoon** [comment]
Hello Allen,

Thank you so much for contacting us. Unfortunately, our PyRFA cannot
install via pip yet. By the way, you can install PyRFA following the
instructions below:

1. You can download the PyRFA package which matches your platform via
https://github.com/devcartel/thomsonreuters
2. Also, we've provided the install instruction in this link:
https://github.com/devcartel/thomsonreuters/blob/master/PYRFA8.md#installation

Thank you so much,
Ukrit H.

**Comment by wiwat-tharateeraparb** [comment]
Would running `pip install` directly from download links be fine? PyRFA already has `setup.py` in the package.

Example:
```
pip install --upgrade https://github.com/devcartel/thomsonreuters/releases/download/pyrfa8.0.1.1/pyrfa8.0.1.1-linux-x86_64-py27.zip
```

**Comment by HangingClowns** [comment]
Seems that

**Comment by wiwat-tharateeraparb** [comment]
@HangingClowns PyRFA is now on PyPI. You can just use pip to install PyRFA with `pip install pyrfa`.
