### ISSUE TITLE
pyrfa in .NET?

### ISSUE THREAD

**Issue by laurentbeaumer** [devcartel/pyrfa#21]
Hi

I have been trying to call pyrfa from .NET (C#). 

It doesn't work with IronPython as the latter doesn't support pyd files.

So I am now trying with Python .NET (pythonnet). 

Using Python .NET, the code creates a dynamic object from pyrfa.

I have been trying to invoke/use different methods ("createConfigDb", etc.) but I get an error like:
"'Python.Runtime.PyObject' does not contain a definition for 'createConfigDb'"

My question: is there a way to call pyrfa from C#/.NET?

Thanks

**Comment by wiwat-tharateeraparb** [comment]
I've never tried but I don't think that's possible as PyRFA is built with C/C++.

**Comment by laurentbeaumer** [comment]
Thanks, it was a quick reply.

Just for information, Python .NET is wrapper around pythonXX.dll and uses P/Invoke, the same way for any DLL with unmanaged code (including C/C++). 

For example, it works with NumPy. So theoretically, it could have worked with PyRFA...

**Comment by wiwat-tharateeraparb** [comment]
Can you `import pyrfa` in pythonnet?

**Comment by ehouarn-perret** [comment]
@laurentbeaumer, agreed, it might do the trick. 
Actually, it can be boiled down to just a matter of language A, Python being consumed by another language B aka .NET C#.

**Comment by laurentbeaumer** [comment]
I have posted the issue also on the Github of pythonnet, and it has been resolved:
https://github.com/pythonnet/pythonnet/issues/266

**Comment by laurentbeaumer** [comment]
Thanks all

**Comment by wiwat-tharateeraparb** [comment]
PyRFA 8.0.2 now supports unicode strings. Hope this makes you.
