### ISSUE TITLE
PyRFA for Python 3.6

### ISSUE THREAD

**Issue by xsarm06** [devcartel/pyrfa#23]
May I ask when will be the realese of PyRFA for Python 3.6 ready?

**Comment by ukrit-himakoon** [comment]
Hello xsarm06.

One question, what's the platform and OS version that you expect to run
PyRFA if it supports Python3.6?

Thank you so much,
Ukrit H.

**Comment by wiwat-tharateeraparb** [comment]
@xsarm06 There is a plan to support Python3.6 for both Windows and Linux but cannot confirm the ETA at this moment. However, if you are in our [Enterprise](http://devcartel.com/enterprise) program, you can request for the build.

**Comment by wiwat-tharateeraparb** [comment]
Just released PyRFA 8.1.0 today and it supports Python 3.6 on both Linux and Windows. It is now available from PyPI from now on.
