### ISSUE TITLE
Error pulling SymbolList

### ISSUE THREAD

**Issue by kodeaway** [devcartel/pyrfa#31]
Getting errors while using getSymbolList

Debug is ON and am able to see the below.

[SymbolListHandler::decodeSymbolList] Expected key buffer databuffer type of Buffer
({'MTYPE' : 'REFRESH','RIC' : 'SL RICNAME','SERVICE' : 'SERVICENAME'})

SymbolList are being pulled OK with other tools without any issues.

**Comment by wiwat-tharateeraparb** [comment]
Are you referring to a chain RIC? Thomson Reuters has legacy, unstructured chain RIC data model for delivery of a list of symbols. SymbolList (OMM) is a newer structured which is only available from TRDF-D feeds (Direct Feed for exchanges). Typically if you want a list of symbols from, say, 0#RIC from IDN, it is most likely that you are requesting for a chain RIC and not a SymbolList.

To pull a chain RIC with PyRFA, you can see code in this [post](http://devcartel.com/blog/14147922) and repost here:

```python
def expandChainRIC(self, chainRIC):
        expanded = []
        done = False
        snapshot = self.snapshotRequest([chainRIC])
        while not done:
            if not snapshot:
                break
            for i in ['LINK_1', 'LINK_2', 'LINK_3', 'LINK_4', 'LINK_5', 'LINK_6', 'LINK_7', 'LINK_8', 'LINK_9', 'LINK_10', 'LINK_11', 'LINK_12', 'LINK_13', 'LINK_14', 'LONGLINK1', 'LONGLINK2', 'LONGLINK3', 'LONGLINK4', 'LONGLINK5', 'LONGLINK6', 'LONGLINK7', 'LONGLINK8', 'LONGLINK9', 'LONGLINK10', 'LONGLINK11', 'LONGLINK12', 'LONGLINK13', 'LONGLINK14']:
                if snapshot[0][2].has_key(i) and snapshot[0][2][i]:
                    expanded.append(snapshot[0][2][i])
            if snapshot[0][2].has_key('NEXT_LR') and snapshot[0][2]['NEXT_LR']:
                snapshot = self.snapshotRequest([snapshot[0][2]['NEXT_LR']])
            elif snapshot[0][2].has_key('LONGNEXTLR') and snapshot[0][2]['LONGNEXTLR']:
                snapshot = self.snapshotRequest([snapshot[0][2]['LONGNEXTLR']])
            else:
                done = True
        # if chainRIC is not a chain, return itself back
        if not expanded:
            expanded.append(chainRIC)
        if self.debug:
            print "[debug] Expand chain " + chainRIC + " -> " + str(expanded)
        return expanded
```
and
```python
def snapshotRequest(self, ricList):
        snaphots = ()
        self.pyrfa.log("Subscribing items: " + str(ricList) + " (total: " + str(len(ricList)) + " )")
        for ric in ricList:
            self.pyrfa.marketPriceRequest(ric)
        global end
        end = False
        t = threading.Timer(10, stop)
        t.start()
        imageReceived = 0
        while not end and imageReceived < len(ricList):
            images = self.pyrfa.dispatchEventQueue()
            if images:
                for i in images:
                    if type(i[2]) is dict:
                        imageReceived += 1
                        snaphots += (i,)
                        t.cancel()
                        t = threading.Timer(10, stop)
                        t.start()
        self.pyrfa.log("Snapshots received: " + str(imageReceived))
        t.cancel()
        return snaphots
```

**Comment by kodeaway** [comment]
Thanks for the reply.
This is a symbollist. Domain 10 if I have to use rmdstestclient.

Against a TRDFD this SymbolList sample code works. It does not work against a service hosted by Reuters which only supports SymbolLists and does not support chain RICs.

**Comment by wiwat-tharateeraparb** [comment]
Are you able to email us the log file to take a look? Email: support@devcartel.com

**Comment by clgoldman** [comment]
Our support team found a difference in one of the parameters returned from RDFD vs. the new service.

RDFD

<refreshMsg rwfMajorVer="0" rwfMinorVer="0" mType="RWF_MT_SYMBOL_LIST" streamId="5" dataFormat="RSSL_DF_MAP" refreshFlags="0x1A8" groupId ="1" qosDynamic="0" qosRate="1" qosTimeliness="1" dataState="RSSL_DATA_OK" streamState="RSSL_STREAM_OPEN" code="RSSL_SC_NONE" text="Request In Progress"  dataSize="1263">
    <key  flags="0x3" serviceId="63" name="0#OPRA"/>
    <dataBody>
        <map flags="2" countHint="0" keyDataType="RSSL_DT_BUFFER" dataFormat="RSSL_DF_FIELD_LIST" >


New service:
<refreshMsg rwfMajorVer="0" rwfMinorVer="0" mType="RWF_MT_SYMBOL_LIST" streamId="5" dataFormat="RSSL_DF_MAP" refreshFlags="0x10A8" groupId ="11" qosDynamic="0" qosRate="1" qosTimeliness="1" dataState="RSSL_DATA_OK" streamState="RSSL_STREAM_NON_STREAMING" code="RSSL_SC_NONE" text=""  dataSize="2713">
    <key  flags="0x3" serviceId="273" name="0#OPRA"/>
    <dataBody>
        <map flags="0" countHint="0" keyDataType="RSSL_DT_RMTES_STRING" dataFormat="RSSL_DF_FIELD_LIST" >


Is the difference in the keyDataType (RSSL_DT_BUFFER vs RSSL_DT_RMTES_STRING)  causing the issue  with pyRFA ?

**Comment by wiwat-tharateeraparb** [comment]
Yes. We didn't expect Symbol List to be encoded as RMTES string. Will fix this in the next release.

**Comment by wiwat-tharateeraparb** [comment]
Please try PyRFA 8.2.1 released today for which addresses this issue.

**Comment by clgoldman** [comment]
Thank you for this quick turnaround.   I'll let you know the results

**Comment by kodeaway** [comment]
This fixed the problem we were seeing. Thank you very much for the fix.
