### ISSUE TITLE
Service/Capability list

### ISSUE THREAD

**Issue by billr916** [devcartel/pyrfa#35]
Hi, You have the directoryRequest() method which I guess returns service information. Is there any way to access/reference this info.

**Comment by wiwat-tharateeraparb** [comment]
Currently there is no output data for `directoryRequest()`. It only logs directory response to the log file. We plan to include this in the future release.

**Comment by billr916** [comment]
Hi, Thanks for the prompt response, Great API !!! really useful !!!

**Comment by wiwat-tharateeraparb** [comment]
Released today PyRFA 8.3.0 `directoryRequest()` now returns a tuple of service information. See https://github.com/devcartel/pyrfa/blob/master/API.md#directory for more detail.
