### ISSUE TITLE
Hanging time series request

### ISSUE THREAD

**Issue by vmarunov** [devcartel/pyrfa#44]
If requesting TS after TS-request which return empty response (e.g. invalid RIC), then request may be hang. When request hang, python process has 100% cpu utilisation.

Not all RIC give this effect.

For example:

Process hang:
```python
import pyrfa
p = pyrfa.Pyrfa()
p.createConfigDb('./pyrfa.cfg')
p.acquireSession('Session1')
p.createOMMConsumer()
p.login()
p.directoryRequest()
p.dictionaryRequest()
p.setTimeSeriesPeriod('daily')
ts = p.getTimeSeries('AAA')
ts = p.getTimeSeries('ZMW=')
```

Process not hang:
```python
import pyrfa
p = pyrfa.Pyrfa()
p.createConfigDb('./pyrfa.cfg')
p.acquireSession('Session1')
p.createOMMConsumer()
p.login()
p.directoryRequest()
p.dictionaryRequest()
p.setTimeSeriesPeriod('daily')
ts = p.getTimeSeries('AAA')
ts = p.getTimeSeries('EUR=')
```

**Comment by wiwat-tharateeraparb** [comment]
Can you upload the PyRFA log file?

**Comment by vmarunov** [comment]
@wiwat-tharateeraparb 
pyrfa log and console log in attachment.
[log.zip](https://github.com/devcartel/pyrfa/files/2323712/log.zip)

**Comment by wiwat-tharateeraparb** [comment]
@vmarunov What if you run it without prior undefined RIC 'AAA' e.g.:

```python
import pyrfa
p = pyrfa.Pyrfa()
p.createConfigDb('./pyrfa.cfg')
p.acquireSession('Session1')
p.createOMMConsumer()
p.login()
p.directoryRequest()
p.dictionaryRequest()
p.setTimeSeriesPeriod('daily')
ts = p.getTimeSeries('ZMW=')
```

Would you run into the same situation?

**Comment by vmarunov** [comment]
@wiwat-tharateeraparb If I run it without prior undefined RIC then all request pass normally.

**Comment by wiwat-tharateeraparb** [comment]
@vmarunov We might have a fix but we don't have ZMW= timeseries data to test. Are you able to help us test? If so, please send an email to our support@devcartel.com and we will send a new binary to test out. Thanks.

**Comment by wiwat-tharateeraparb** [comment]
8.5.2 released today fixes this issue. (Thanks @vmarunov for helping with the test)

**Comment by vmarunov** [comment]
@wiwat-tharateeraparb Thanks
