### ISSUE TITLE
Python 3.7 support?

### ISSUE THREAD

**Issue by snb2013** [devcartel/pyrfa#47]
It is impossible now. When it will be available?

**Comment by wiwat-tharateeraparb** [comment]
Support for Python 3.7 will be available for our [Enterprise](http://devcartel.com/pyrfa-enterprise) subscribers version 8.5.3 around end of November 2018. Public released will be around December.

**Comment by snb2013** [comment]
Ok, thank you!

**Comment by wiwat-tharateeraparb** [comment]
Hi, PyRFA 8.5.3 with Python 3.7 support is released on [PyPI](https://pypi.org/project/pyrfa/).
