### ISSUE TITLE
fields subsetting

### ISSUE THREAD

**Issue by iposter2016** [devcartel/pyrfa#49]
RFA java has an ability to let you see updates only for a subset of fields. Is this already available on pyrfa or will it be any time soon?
Thanks.

**Comment by wiwat-tharateeraparb** [comment]
It is already supported in PyRFA. It's called View and can be use with `Pyrfa.setView()`

**Comment by iposter2016** [comment]
Thanks. I see the function but am not sure how to set the fields I'd like.

**Comment by iposter2016** [comment]
I figured it out. Thanks.
